

export type ObsidianMdLoaderOptions = {
  /** The glob pattern to match files, relative to the base directory. Defaults to **\/*.md  */
  pattern?: string | Array<string>;
  /** The glob pattern to match assets, relative to the base directory. Defaults to **\/*.{svg,png,jpg,jpeg,avif,webp,gif,tiff,ico}  */
  assetsPattern?: string | Array<string>;
  /** The base directory to resolve the glob pattern from. Relative to the root directory, or an absolute file URL. Defaults to `.` */
  base?: string | URL;
  /** Enables i18n routing */
  i18n?: boolean;
  /** Base URL where this content should be served. Defaults to collection name. Used for autogenerated permalink */
  url?: string;
  /** Default author */
  author?: string;
  /** Broken links strategy. Defaults to "plaintext".
   * warn: logs a warning but renders the link anyway
   * plaintext: removes the link but keeps the label
   * 404: replaces the link with a parametrised link to 404 page
   **/
  brokenLinksStrategy?: 'warn' | 'label' | '404';
  /** Remove h1 from document. Useful if your h1 is the same as the document title. Default true */
  removeH1?: boolean;
};

export type ObsidianContext = {
  author?: string;
  assets: string[];
  entry: string;
  files: string[];
  base: string;
  baseUrl: string;
  i18n?: boolean;
  defaultLocale?: string;
  options: ObsidianMdLoaderOptions;
};